spring.application.name=spendingTracker


spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=spendingTracker

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
jwt.secret=${JWT_SECRET}

####google.client.secret=${GOOGLE_CLIENT_SECRET}
google.client.id=${GOOGLE_CLIENT_ID}
server.port=${PORT:8080}